app:
  scheduler:
    enable: true
    interval: 20s
    force-check-delay: 10s
  database-access-type: jpa

spring:
  application:
    name: scrapper
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

server:
  port: 8080
springdoc.swagger-ui.path: /swagger-ui
logging:
  config: classpath:log4j2-plain.xml
