app:
  scheduler:
    enable: true
    interval: 20s
    force-check-delay: 10s
  database-access-type: jdbc
  retry:
    type: CONSTANT
    statusCode: [500,501,502,503,504,505,506,507,508,509,510]
    delay: 5000
    attempts: 3
  kafka:
    bootstrap-servers: localhost:9092
    topic: "newUpdate"
  useQueue: true

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8080
springdoc.swagger-ui.path: /swagger-ui
logging:
  config: classpath:log4j2-plain.xml
