app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
  retry:
    type: EXPONENTIAL
    statusCode: [ 500,501,502,503,504,505,506,507,508,509,510]
    delay: 5000
    attempts: 3
  kafka:
    bootstrap-servers: localhost:9092
    topic: "newUpdate"
    group-id: "botUpdates"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
springdoc.swagger-ui.path: /swagger-ui
server:
  port: 8090
management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health,prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true



logging:
  config: classpath:log4j2-plain.xml
